FROM python:3.10.12

LABEL org.opencontainers.image.source=https://github.com/kwsni/Gamblino
LABEL org.opencontainers.image.title="gamblino-web"
LABEL org.opencontainers.image.description="Web interface for a CS:GO/CS2 crate opening simulator as a Discord Bot"
LABEL org.opencontainers.image.version=0.2.0
LABEL org.opencontainers.image.licenses=MIT

WORKDIR /usr/src/gamblino-web/

COPY web/. .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["gunicorn", "gamblino.wsgi", "-b", ":8000"]
