# Generated by Django 5.1.4 on 2025-03-10 21:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=9)),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('rarity', models.CharField(default='', max_length=24)),
                ('wear', models.CharField(default='', max_length=24)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.case')),
            ],
        ),
        migrations.CreateModel(
            name='InvItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date opened')),
                ('inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item')),
            ],
        ),
    ]
