# Generated by Django 5.1.4 on 2025-04-17 06:13

import django.db.models.deletion
import django.utils.timezone
import inventory.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=9)),
                ('name', models.CharField(default='', max_length=200, unique=True)),
                ('image', models.ImageField(upload_to=inventory.models.img_dir_path)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialaccount.socialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, unique=True)),
                ('rarity', models.CharField(choices=[(None, 'Null'), ('Covert', 'Covert'), ('Classified', 'Classified'), ('Restricted', 'Restricted'), ('Mil-Spec Grade', 'Mil-Spec Grade')], default='Null', max_length=16)),
                ('image', models.ImageField(upload_to=inventory.models.img_dir_path)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.case')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wear', models.CharField(choices=[(None, 'Null'), ('Factory New', 'Factory New'), ('Minimal Wear', 'Minimal Wear'), ('Field-Tested', 'Field-Tested'), ('Well-Worn', 'Well-Worn'), ('Battle-Scarred', 'Battle-Scarred')], default='Null', max_length=16)),
                ('stattrak', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='InvItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date opened')),
                ('inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itemprice')),
            ],
        ),
    ]
