# Generated by Django 5.1.4 on 2025-03-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_user_alter_invitem_item_alter_item_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.URLField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=48),
        ),
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(choices=[(None, 'Null'), ('Rare', 'Rare'), ('Covert', 'Covert'), ('Classified', 'Classified'), ('Restricted', 'Restricted'), ('Mil-Spec', 'Mil-Spec')], default='Null', max_length=16),
        ),
        migrations.AlterField(
            model_name='item',
            name='wear',
            field=models.CharField(choices=[(None, 'Null'), ('Factory New', 'Factory New'), ('Minimal Wear', 'Minimal Wear'), ('Field-Tested', 'Field-Tested'), ('Well-Worn', 'Well-Worn'), ('Battle-Scarred', 'Battle-Scarred')], default='Null', max_length=16),
        ),
    ]
