# Generated by Django 5.1.4 on 2025-03-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_image_alter_item_name_alter_item_rarity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
