# Generated by Django 5.1.4 on 2025-03-11 19:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='wear',
        ),
        migrations.AddField(
            model_name='case',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.CreateModel(
            name='ItemWear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wear', models.CharField(choices=[(None, 'Null'), ('Factory New', 'Factory New'), ('Minimal Wear', 'Minimal Wear'), ('Field-Tested', 'Field-Tested'), ('Well-Worn', 'Well-Worn'), ('Battle-Scarred', 'Battle-Scarred')], default='Null', max_length=16)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
        migrations.AlterField(
            model_name='invitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itemwear'),
        ),
    ]
