# Generated by Django 5.1.4 on 2024-12-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
