# Generated by Django 5.1.4 on 2025-03-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
