# Generated by Django 5.1.4 on 2025-02-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_item_case_remove_item_user_user_name_useritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='users',
            field=models.ManyToManyField(to='user.user'),
        ),
        migrations.DeleteModel(
            name='UserItem',
        ),
    ]
