# Generated by Django 5.1.4 on 2025-03-08 05:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
    ]
