# Generated by Django 5.1.4 on 2025-02-20 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_item_users_delete_useritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='users',
        ),
        migrations.AddField(
            model_name='case',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.item'),
        ),
        migrations.AddField(
            model_name='user',
            name='items',
            field=models.ManyToManyField(to='user.item'),
        ),
    ]
