# Generated by Django 5.1.4 on 2025-02-20 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_item_users_case_items_user_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.case'),
        ),
    ]
