# Generated by Django 5.1.4 on 2025-03-10 17:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_player_cash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='player',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='playeritem',
            name='rarity',
        ),
        migrations.AddField(
            model_name='item',
            name='rarity',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='playeritem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='case',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='playeritem',
            name='wear',
            field=models.CharField(default='', max_length=24),
        ),
    ]
