# Generated by Django 5.1.4 on 2025-02-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_case_items_item_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='items',
            new_name='case',
        ),
    ]
