# Generated by Django 5.1.4 on 2025-03-10 19:34

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_item_price_remove_player_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playeritem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='playeritem',
            name='wear',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9),
        ),
        migrations.AddField(
            model_name='item',
            name='wear',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='playeritem',
            name='opened_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date opened'),
        ),
    ]
